ADD: 입금내역(deposit) API 추가
2021-3q-wecode-payhere-intern/go-gin-codef-api pull request #1
Opened 2021-07-13 03:54 UTC by BG-YU

## 요약
  -  일별 입금내역 추가
  - 카드사별 입금내역 추가

## 상세
  -  일별 입금내역 추가
     - 월단위 일자별 입금금액 내역
     - 월단위 총 입금금액
  
  - 카드사별 입금내역 추가
    - 일단위 카드사별 입금금액 내역
    - 일단위 총 입금금액

2021-07-13 06:33 UTC, szto requested changes
api 작성하실 때는 api 문서가 없으면 README 에 parameter 와 response 가 어떻게 되는지 기록해 주시면 좋을것 같습니다. 그렇지 않으면 어떤 api 를 만드신 것인지 알기가 쉽지 않습니다. 우선 서비스 로직 쪽만 분리해 주시면 감사드리겠습니다.

2021-07-13 06:33 UTC, szto commented on db/dbconn.go
> +	// init config
p1: 여기 코멘트는 필요 없을것 같아서 삭제해 주세요.

2021-07-13 06:33 UTC, szto commented on main.go
> +	}
ask: 이 부분은 한 달이 31일이 마지막 날이 아닌 경우에도 상관이 없을까요?

2021-07-13 06:33 UTC, szto commented on main.go
> +	}
p2: 이 부분은 서비스 형태로 만들면 좋을것 같습니다. 따로 함수를 만들어서 계산하는 로직을 구분해서 만들어주시면 좋을것 같습니다.

2021-07-13 06:33 UTC, szto commented on main.go
> +	}
여기도 위와 같이 서비스 로직으로 분리해 주시면 좋겠습니다.

2021-07-13 09:08 UTC, BG-YU commented on db/dbconn.go
> +	// init config
f19ac296446907dd961487f300b0e2ff801aea16 수정 완료 하였습니다.

2021-07-13 09:16 UTC, BG-YU commented on main.go
> +	}
27bb7b1ed968650c459b31fe53e33be799a812e4
string값이라 mongodb에서도 딱히 에러가 없어, 간단하게 처리해본다고 했던 로직이었습니다..
마지막날 값 받아 올수 있도록 수정 완료하였습니다!

2021-07-13 09:19 UTC, BG-YU commented on main.go
> +	}
27bb7b1ed968650c459b31fe53e33be799a812e4 수정 완료하였습니다!

2021-07-13 09:22 UTC, BG-YU commented on main.go
> +	}
27bb7b1ed968650c459b31fe53e33be799a812e4 수정 완료하였습니다!

다음부터는 변경내용을 좀 더 깔끔하게 보실 수 있도록 commit관리에 주의하겠습니다!
(변경내용을 너무 한꺼번에 올려버려서 변경내용이 무엇인지 제가 봐도 좀 헷갈리네요...)

2021-07-13 09:30 UTC, BG-YU commented
> api 작성하실 때는 api 문서가 없으면 README 에 parameter 와 response 가 어떻게 되는지 기록해 주시면 좋을것 같습니다. 그렇지 않으면 어떤 api 를 만드신 것인지 알기가 쉽지 않습니다. 우선 서비스 로직 쪽만 분리해 주시면 감사드리겠습니다.


> api 작성하실 때는 api 문서가 없으면 README 에 parameter 와 response 가 어떻게 되는지 기록해 주시면 좋을것 같습니다. 그렇지 않으면 어떤 api 를 만드신 것인지 알기가 쉽지 않습니다. 우선 서비스 로직 쪽만 분리해 주시면 감사드리겠습니다.
27bb7b1ed968650c459b31fe53e33be799a812e4 어떤식으로 작성하면 좋을지 검토 받고 싶어, 작성 해보았습니다!

2021-07-13 09:32 UTC, BG-YU commented
> > api 작성하실 때는 api 문서가 없으면 README 에 parameter 와 response 가 어떻게 되는지 기록해 주시면 좋을것 같습니다. 그렇지 않으면 어떤 api 를 만드신 것인지 알기가 쉽지 않습니다. 우선 서비스 로직 쪽만 분리해 주시면 감사드리겠습니다.
> 
> > api 작성하실 때는 api 문서가 없으면 README 에 parameter 와 response 가 어떻게 되는지 기록해 주시면 좋을것 같습니다. 그렇지 않으면 어떤 api 를 만드신 것인지 알기가 쉽지 않습니다. 우선 서비스 로직 쪽만 분리해 주시면 감사드리겠습니다.
> > [27bb7b1](https://github.com/2021-3q-wecode-payhere-intern/go-gin-codef-api/commit/27bb7b1ed968650c459b31fe53e33be799a812e4) 어떤식으로 작성하면 좋을지 검토 받고 싶어, 작성 해보았습니다!

2021-07-13 13:58 UTC, AhnSeongHyun commented on README.MD
> +### URI : /deposit
http method를 붙여주면 더 좋을거 같아요 
```suggestion
### URI : [GET] /deposit
```

2021-07-14 00:52 UTC, BG-YU commented on README.MD
> +### URI : /deposit
3f30a39eafe7e1b931fd9f49e278cb0b103dabcf 리뷰 감사드립니다!
수정 완료하였습니다.

2021-07-14 03:25 UTC, AhnSeongHyun approved these changes

2021-07-14 03:26 UTC, merged