ADD: 휴폐업 상태 조회 기능 추가
2021-3q-wecode-payhere-intern/go-gin-codef-api pull request #2
Opened 2021-07-14 06:39 UTC by BG-YU

## 요약
 - 휴폐업 상태 조회 기능 추가

## 상세
 - 휴폐업 상태 조회 기능 추가
   - 사업자등록 번호 단건 또는 다건으로 매장의 휴폐업 상태를 조회 하는 기능 추가

2021-07-14 06:56 UTC, AhnSeongHyun requested changes

2021-07-14 06:56 UTC, AhnSeongHyun commented on README.MD
> +###  URI : [GET] /storestatus
```suggestion
###  URI : [GET] /business/status
```
저희가 내부적으로 store 라는 것은 특정경우에만(온라인 스토어)사용하고 있어서 business가 나을것 같고, 이후 사업자 관련 다른 조회도 있을것 같아서 하나 분리시켜서 가면 좋을것 같습니다.

2021-07-14 06:56 UTC, AhnSeongHyun commented on README.MD
> +     - parameter : identity
```suggestion
     - parameter : biz_number
```
내부 워딩이  biz_number로 사용하고 있어서 이걸로 해주세요. 그리고 사업자 등록번호 10자리 대시(-) 포함해서 받는것으로 해주세요. codef로 넘길때 replace 처리해 주시면 될 것 같습니다.

2021-07-14 06:56 UTC, AhnSeongHyun commented on README.MD
> +     - 다건 : 1122334455,2222334455
다건 케이스는 아예 빼주세요. 하나의 API에서 다른 2개의 동작을 하는건 좋지 않습니다. 이런 경우 API Endpoint를 2개 파는게 낫습니다.

2021-07-14 06:56 UTC, AhnSeongHyun commented on storestatus/storestatus.go
> +		"organization":    "0004",
"0004" 상수화 해주세요.

2021-07-14 06:56 UTC, AhnSeongHyun commented on config/config.go
> +		CrefiaPassword:    os.Getenv("CREFIA_PASSWORD"),
ask; 제가 잘 모르는 부분인데 이 id, password는 어디에서 사용하는 건가요?

2021-07-14 06:56 UTC, AhnSeongHyun commented on storestatus/storestatus.go
> +
generateErrorMsg 같은 함수로 분리시키면 좋을것 같습니다.

2021-07-14 08:26 UTC, BG-YU commented on README.MD
> +###  URI : [GET] /storestatus
715816d3c1d3ae3d6c1119f146e5f20e4db51c5c 수정 완료하였습니다!

2021-07-14 08:27 UTC, BG-YU commented on README.MD
> +     - parameter : identity
715816d3c1d3ae3d6c1119f146e5f20e4db51c5c 수정 완료하였습니다!

2021-07-14 08:27 UTC, BG-YU commented on README.MD
> +     - 다건 : 1122334455,2222334455
715816d3c1d3ae3d6c1119f146e5f20e4db51c5c 수정 완료하였습니다!

2021-07-14 08:28 UTC, BG-YU commented on storestatus/storestatus.go
> +		"organization":    "0004",
90bc6bb63cfcabc044d39ca63fa2a745dda3a072 수정 완료하였습니다!

2021-07-14 08:29 UTC, BG-YU commented on config/config.go
> +		CrefiaPassword:    os.Getenv("CREFIA_PASSWORD"),
90bc6bb63cfcabc044d39ca63fa2a745dda3a072 아 사용하지 않는 config 값들입니다. 삭제 완료하였습니다.

2021-07-14 08:29 UTC, BG-YU commented on storestatus/storestatus.go
> +
8dd2d6190c49038a0aca12c63abe409defa8075e 수정 완료하였습니다!

2021-07-14 09:42 UTC, AhnSeongHyun approved these changes
LGTM :)

2021-07-14 14:01 UTC, szto reviewed
go.mod 는 최상위에만 존재해도 될 것 같습니다. 모듈이 불필요하게 폴더마다 설치되어 있는것 같아요.

2021-07-15 01:42 UTC, BG-YU commented
> go.mod 는 최상위에만 존재해도 될 것 같습니다. 모듈이 불필요하게 폴더마다 설치되어 있는것 같아요.

089820534bc3b17380c55f38f2500e4811d488ee 리뷰 감사드립니다!
불필요한 go.mod 삭제 완료하였습니다!

2021-07-15 01:47 UTC, szto approved these changes

2021-07-15 01:48 UTC, szto commented
고생하셨습니다. 승인했습니다.

2021-07-15 03:05 UTC, merged