Feature/code refactoring
2021-3q-wecode-payhere-intern/go-gin-codef-api pull request #3
Opened 2021-07-21 03:07 UTC by BG-YU

# 요약
 - 코드 리팩토링
 - Dockerfile 생성

# 상세
 - 코드 리팩토링
   - 소스 파일을 src 폴더로 분리
     - codef :  Codef 인스턴스 생성 및 Codef 서비스 타입 함수
     - db : Database인스턴스 생성
     - config : 환경변수 설정
     - controller : 기능 구분에 따른 service로직 호출
     - router : endpoint에 따른 controller 호출
     - service : 비지니스 로직 실행
     - utils : 기능별 공통함수 및 유효성 체크, 에러 메세지 함수
     - message : response message 모음
     - properties : 속성 값 모음
   - Dockerfile 생성
# 폴더구조
```bash
.
├── Dockerfile
├── README.MD
├── go.mod
├── go.sum
├── main.go
└── src
    ├── codef
    │   └── codef.go
    ├── config
    │   └── config.go
    ├── controller
    │   ├── business.go
    │   └── deposit.go
    ├── db
    │   ├── dbconn.go
    │   └── mongo.go
    ├── message
    │   └── message.go
    ├── properties
    │   └── properties.go
    ├── router
    │   └── router.go
    ├── service
    │   ├── business.go
    │   └── deposit.go
    └── utils
        ├── date.go
        ├── error.go
        └── validation.go
```

2021-07-21 04:44 UTC, szto requested changes

2021-07-21 04:44 UTC, szto commented on docker/Dockerfile
> +CMD ["go","run","."]
p1: end of file ( line 띄워주시면 좋겠습니다. ) 그리고 dockerfile 보통은 build 만 시키고 실행은 따로 하시는 방식으로 많이 합니다. docker run은 테스트 시에만 사용하신다고 보시면 좋겠습니다.

2021-07-21 04:44 UTC, szto commented on src/controller/business.go
> +		c.JSON(http.StatusOK, gin.H{
```suggestion
	if len(codefResult.Data) == 0 {
		c.JSON(http.StatusOK, gin.H{
```
p2: len이 0 보다 작을 경우가 없을것 같습니다.

2021-07-21 04:44 UTC, szto commented on src/service/business.go
> +}
p2:  entity 폴더 만들어서 나눠주시면 좋을것 같습니다.

2021-07-21 04:44 UTC, szto commented on src/service/deposit.go
> +}
entity 폴더 나눠주세요~

2021-07-21 04:44 UTC, szto commented on src/utils/validation.go
> +}
p2: 이 패키지는 request package 를 만드시면 더 좋을것 같습니다.

2021-07-22 01:21 UTC, BG-YU commented on docker/Dockerfile
> +CMD ["go","run","."]
9931b30b437ec9934aada23cab68617eee656f1b 리뷰 감사드립니다!
수정 완료하였습니다.

2021-07-22 01:21 UTC, BG-YU commented on src/controller/business.go
> +		c.JSON(http.StatusOK, gin.H{
ed8607d24630603f94177d5cb40a9071e4dbca04 수정 완료하였습니다!

2021-07-22 01:22 UTC, BG-YU commented on src/service/business.go
> +}
ed8607d24630603f94177d5cb40a9071e4dbca04 수정 완료하였습니다!

2021-07-22 01:23 UTC, BG-YU commented on src/service/deposit.go
> +}
7a68a17c6f2a40891bcfe07a03493f02b2f9955c 수정 완료하였습니다!

2021-07-22 01:23 UTC, BG-YU commented on src/utils/validation.go
> +}
f45cef82e092f2c5e47805783e7230e5c6b3493c 수정 완료하였습니다!

2021-07-22 01:27 UTC, BG-YU commented on src/utils/validation.go
> +}
a57edaad952fbadd188bff02259673fa6ba1ee56 response문자가 중복이라 response문자 제거 하였습니다.

2021-07-22 07:06 UTC, szto approved these changes

2021-07-22 07:11 UTC, merged